import type { Metadata } from "next";
import NavbarWrapper from "@/components/NavbarWrapper";
import "./globals.css";
import MTThemeProvider from "@/Providers/ThemeProvider";

export const metadata: Metadata = {
  title: "Wire wave",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>
        <MTThemeProvider>
          <NavbarWrapper>{children}</NavbarWrapper>
        </MTThemeProvider>
      </body>
    </html>
  );
}
